package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.MessageDO;

public interface MessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Dec 08 21:48:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Dec 08 21:48:39 CST 2019
     */
    int insert(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Dec 08 21:48:39 CST 2019
     */
    int insertSelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Dec 08 21:48:39 CST 2019
     */
    MessageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Dec 08 21:48:39 CST 2019
     */
    int updateByPrimaryKeySelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbg.generated Sun Dec 08 21:48:39 CST 2019
     */
    int updateByPrimaryKey(MessageDO record);
}